### ISSUE TITLE
Infuse doesn't actually reflect changes

### ISSUE THREAD

**Issue by theg00s3** [firecore/InfuseSync#11]
This is an odd issue, but I'm not sure if it's an issue with the plugin or the app itself, but for some reason the app never shows changes. For example, if a new episode of show X is added to the Jellyfin library, it will not show up in the app despite the number of times I hit scan for changes. The only way to fix it is to remove the server from Infuse and re-add it.

Edit: versions:
InfuseSync 1.3.3.0
Infuse Pro 7.1.3

**Comment by minoskt** [comment]
Same for me. I reported this a while ago here: https://community.firecore.com/t/jellyfin-and-indexing-syncing/28835

**Comment by theg00s3** [comment]
well that's something fun and very disappointing to hear as a semi-recent lifetime pro owner

**Comment by minoskt** [comment]
In the upcoming features page, for 7.2.2 they mention:
`Enhancements and optimizations for Emby/Jellyfin`

I am sure they are working on this.

**Comment by theg00s3** [comment]
fingers crossed. I feel like syncing has been broken for a while now, even ignoring the jellyfin plugin

**Comment by minoskt** [comment]
I personally no longer have these issues since the last update (Infuse v7.3 with InfuseSync v1.4.1).

**Comment by theg00s3** [comment]
same here
