### ISSUE TITLE
Limited Genres

### ISSUE THREAD

**Issue by dannymichel** [firecore/InfuseSync#14]
Only 9 of tv show genres show for jellyfin. Plex shows many

**Comment by dannymichel** [comment]
https://github.com/jellyfin/jellyfin/issues/7773 they’re saying it’s an infuse issue
![1056B312-D027-40E5-A0C4-976FAC0DB588](https://user-images.githubusercontent.com/1161544/169418939-377b7612-170c-4a61-9d46-e93852232d53.jpg)

**Comment by firecore** [comment]
I would recommend updating to the latest 10.9 version of Jellyfin and Infuse 7.7.7.

You may also consider using [Direct Mode](https://firecore.com/blog/infuse-77-direct-mode) for even faster updates.
