### ISSUE TITLE
nyanmisaka/jellyfin  10.8 ，InfuseSync1.4.2.0 NotSupported

### ISSUE THREAD

**Issue by AntaresXL** [firecore/InfuseSync#15]
DS918 DSM 6.2.4-25556

nyanmisaka/jellyfin  10.8

InfuseSync1.4.2.0
状态： NotSupported

**Comment by leiguan118** [comment]
你的文件库里面现在能看到jellyfin的分类文件夹么？我现在显示意外服务器响应

**Comment by AntaresXL** [comment]
如果你用的是官方10.8那安装1.4.2版本infuse sync应该正常。如果你用的和我一样是nyanmisaka版本，那现在最新版本的infuse sync会提示not support，导致了infuse文件分类显示意外服务器响应。反馈了infuse那边，来往几封邮件还在等待解决

发自我的iPhone

**Comment by nyanmisaka** [comment]
你们是不是还在用去年年底的上古版本，有没有更新到最新的nyanmisaka/jellyfin？ 

我使用最新的5月的，可以成功安装InfuseSync 1.4.2插件，并在重启后生效，Infuse App中扫描也一切正常。

![0](https://user-images.githubusercontent.com/14953024/169572661-4be13162-14a5-402d-987c-83a21d0e9deb.png)

![1](https://user-images.githubusercontent.com/14953024/169572530-b735131c-7a74-443b-b09e-7b9acde80180.png)

![2](https://user-images.githubusercontent.com/14953024/169572800-aabd72c1-c437-4de3-9c91-952dc093c15f.png)

**Comment by nyanmisaka** [comment]
另外建议卸载删除jellyfin的plugins文件夹中的旧版本infuseSync插件，只留最新版。
![0](https://user-images.githubusercontent.com/14953024/169573800-53b249eb-edd5-453d-9990-3b69011f75e0.png)

**Comment by AntaresXL** [comment]
谢谢花费时间回复我的问题
从docker指定版本nyanmisaka/jellyfin:220511-amd64拉取重新创建服务器，现在infusesync 1.4.2已经可以工作了。之前出现问题的服务器一直用的是latest版本。

现在ios infuse有另外一个问题，点击[文件]标签里边可以看到媒体文件夹，再继续点击文件夹会提示“发生错误。意外服务器响应，请重试”
经测试，该问题只有nyanmisaka/jellyfin 10.8服务器会出现。而jellyfin/jellyfin 10.7.6版本可以正常用文件夹形式浏览文件。请问问题是出在哪里呢？（两个测试用的配置均为全新创建）


发自我的iPhone

**Comment by leiguan118** [comment]
> 现在ios infuse有另外一个问题，点击[文件]标签里边可以看到媒体文件夹，再继续点击文件夹会提示“发生错误。意外服务器响应，请重试” 经测试，该问题只有nyanmisaka/jellyfin 10.8服务器会出现。而jellyfin/jellyfin 10.7.6版本可以正常用文件夹形式浏览文件。请问问题是出在哪里呢？（两个测试用的配置均为全新创建） 

你现在的问题就和我一开始提到的一模一样，意外服务器响应

**Comment by nyanmisaka** [comment]
> 从docker指定版本nyanmisaka/jellyfin:220511-amd64拉取重新创建服务器，现在infusesync 1.4.2已经可以工作了。之前出现问题的服务器一直用的是latest版本。

latest版本我每次推送的时候都已经关联了最新日期的tag，可能你用了本地的缓存吧。

> 现在ios infuse有另外一个问题，点击[文件]标签里边可以看到媒体文件夹，再继续点击文件夹会提示“发生错误。意外服务器响应，请重试” 经测试，该问题只有nyanmisaka/jellyfin 10.8服务器会出现。而jellyfin/jellyfin 10.7.6版本可以正常用文件夹形式浏览文件。请问问题是出在哪里呢？（两个测试用的配置均为全新创建）

根据楼上的说法，官方的10.7存在这个问题，并且我没有动过这个部分的源码，所以猜测可能是数据库或者infuse那边存在一个随机的bug，和nyanmisaka/jellyfin没啥关系，你用官方10.8也一样。

我文件夹浏览一切正常，所以暂时没法在我这边复现。

**Comment by jinaoao** [comment]
拉取nyanmisaka最新的镜像（10.80的正式版，6月3号更新）后，同样出现infusesync插件显示not supported，并且在infuse app中文件浏览时显示"发生错误。意外服务器响应，请重试"。

**Comment by leiguan118** [comment]
> 拉取nyanmisaka最新的镜像（10.80的正式版，6月3号更新）后，同样出现infusesync插件显示not supported，并且在infuse app中文件浏览时显示"发生错误。意外服务器响应，请重试"。

我给infuse官方发了消息，这个月十号获得的消息是如下内容
Support for Jellyfin 10.8 will be available as part of the 7.4 update, which will be out within the next few days.

但愿新版本能修复吧。这个问题貌似是大范围出现的，贴吧和infuse论坛上也有其他人反应连不上服务器，而且不止10.8版本，10.7.7也有人吐槽同样的问题，说不会再订阅了

**Comment by jinaoao** [comment]
> > 拉取nyanmisaka最新的镜像（10.80的正式版，6月3号更新）后，同样出现infusesync插件显示not supported，并且在infuse app中文件浏览时显示"发生错误。意外服务器响应，请重试"。
> 
> 我给infuse官方发了消息，这个月十号获得的消息是如下内容 Support for Jellyfin 10.8 will be available as part of the 7.4 update, which will be out within the next few days.
> 
> 但愿新版本能修复吧。这个问题貌似是大范围出现的，贴吧和infuse论坛上也有其他人反应连不上服务器，而且不止10.8版本，10.7.7也有人吐槽同样的问题，说不会再订阅了

但是我昨天更新到nyanmisaka最新的镜像后，jellyfin的server端显示not supported，这个问题不知道是不是infuse的问题

**Comment by AntaresXL** [comment]
我是用了阿里云的docker加速，导致每次拉取的latest版本并不是新的，是很老的版本。你们可以尝试一下不用加速或者换个加速来拉取nyanmisaka大佬的latest版本试试，这个版本确定兼容infusesync 1.4.2。我试过很多次了，最终才发现是我那个阿里云加速出的问题。
另外infuse里边文件夹页面显示错误，意外服务器响应的，这个在7.4版本infuse确实解决了。我之前安装了7.4Beta版本测试过。开发人员很尽责了，耐心等一下吧。
谢谢一直完善功能修复bug的大佬们，辛苦了


发自我的iPhone

**Comment by nyanmisaka** [comment]
> 但是我昨天更新到nyanmisaka最新的镜像后，jellyfin的server端显示not supported，这个问题不知道是不是infuse的问题

国内的docker加速器可能没法同步更新latest标签，请关闭docker加速器，或者直接选择带最新日期的标签进行拉取。否则你可能会拉取到去年的老版本，那是自然不支持新插件的。

**Comment by jinaoao** [comment]
> > 但是我昨天更新到nyanmisaka最新的镜像后，jellyfin的server端显示not supported，这个问题不知道是不是infuse的问题
> 
> 国内的docker加速器可能没法同步更新latest标签，请关闭docker加速器，或者直接选择带最新日期的标签进行拉取。否则你可能会拉取到去年的老版本，那是自然不支持新插件的。

感谢提醒，昨天直接拉取的带日期的镜像，插件正常显示支持了，thx

**Comment by leiguan118** [comment]
> 我是用了阿里云的docker加速，导致每次拉取的latest版本并不是新的，是很老的版本。你们可以尝试一下不用加速或者换个加速来拉取nyanmisaka大佬的latest版本试试，这个版本确定兼容infusesync 1.4.2。我试过很多次了，最终才发现是我那个阿里云加速出的问题。 另外infuse里边文件夹页面显示错误，意外服务器响应的，这个在7.4版本infuse确实解决了。我之前安装了7.4Beta版本测试过。开发人员很尽责了，耐心等一下吧。 谢谢一直完善功能修复bug的大佬们，辛苦了 发自我的iPhone

Infuse是收费软件，修这种恶性bug是他们应该干的，文件库打不开这种bug能拖这么久不更新我也是服气得不行。在他们官方论坛这个问题已经被挂了一个月，而且还不止一个人在下面回复遇到相同问题，今晚上我又看到有老哥在下面回复说他出现这个问题，一直在喷官方没有正式回复，既没更新也没预告。

**Comment by AntaresXL** [comment]
装了测试版本已经修复了这个文件夹错误的bug，不过还是在不停的更新测试版本号，7.4之后得有近十个测试版本了吧，不清楚为啥还不更新商店正式版

发自我的iPhone

**Comment by jinaoao** [comment]
> 装了测试版本已经修复了这个文件夹错误的bug，不过还是在不停的更新测试版本号，7.4之后得有近十个测试版本了吧，不清楚为啥还不更新商店正式版 发自我的iPhone
> […](#)
> 在 2022年6月14日，22:35，Lebranc Caffee ***@***.***> 写道： ﻿ 我是用了阿里云的docker加速，导致每次拉取的latest版本并不是新的，是很老的版本。你们可以尝试一下不用加速或者换个加速来拉取nyanmisaka大佬的latest版本试试，这个版本确定兼容infusesync 1.4.2。我试过很多次了，最终才发现是我那个阿里云加速出的问题。 另外infuse里边文件夹页面显示错误，意外服务器响应的，这个在7.4版本infuse确实解决了。我之前安装了7.4Beta版本测试过。开发人员很尽责了，耐心等一下吧。 谢谢一直完善功能修复bug的大佬们，辛苦了 发自我的iPhone Infuse是收费软件，修这种恶性bug是他们应该干的，文件库打不开这种bug能拖这么久不更新我也是服气得不行。在他们官方论坛这个问题已经被挂了一个月，而且还不止一个人在下面回复遇到相同问题，今晚上我又看到有老哥在下面回复说他出现这个问题，一直在喷官方没有正式回复，既没更新也没预告。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

今天infuse更新商店正式版了（7.4版本）

**Comment by nyanmisaka** [comment]
昨天的infuse 7.4更新日志中正式提到了对jellyfin 10.8的支持，所以我想这个issue大概可以关闭了？

**Comment by farukonfly** [comment]
我这边出现了这样一种情况，在home界面打开tv shows显示的剧集都是不全的，但是通过Files选择jellyfin再选中tv shows里面的剧集又是全的，不知道应该怎么处理。
