### ISSUE TITLE
Blinking and Genre Bug

### ISSUE THREAD

**Issue by dannymichel** [firecore/InfuseSync#16]
In this video you’ll see one of the tv show posters constantly blinking and the fact that I have more than 13 genres of tv shows on Jellyfin but infuse only shows 13. Once I go back to the app you’ll notice a very long refresh. I stop recording after a significant enough time.
https://youtu.be/YxLGMZfzymE

**Comment by firecore** [comment]
I would recommend updating to the latest 10.9 version of Jellyfin and Infuse 7.7.7.

You may also consider using [Direct Mode](https://firecore.com/blog/infuse-77-direct-mode) for even faster updates.
