### ISSUE TITLE
Your username and password combination isn't right

### ISSUE THREAD

**Issue by n0thing2speak** [firecore/InfuseSync#19]
env:
infuse:6.7(3858)
nyanmisaka/jellyfin:10.8.8
InfuseSync1.4.2.0

problem:
when upgraded to the lastest version of jellyfin(10.8.8).  I found that every time I login there will be showing "Your username and password combination isn't right". 
I don't know what the problem is, 10.8.6 is fine.
But it works fine in infuse pro 7.4.10

**Comment by firecore** [comment]
Newer versions of Jellyfin will require Infuse 7 (or later).
