### ISSUE TITLE
Cannot sync movie briefs and actor portrait from emby(4.6.7.0)  to infuse(7.5)4381

### ISSUE THREAD

**Issue by EricJia1242887631** [firecore/InfuseSync#20]
env:
infuse:(7.5)4381
emby:4.6.7.0
InfuseSync1.4.2.0

problem:
1.Cannot sync movie briefs 
2..Cannot sync actor portrait

**Comment by firecore** [comment]
I would recommend updating to the latest 10.9 version of Jellyfin and Infuse 7.7.7.

You may also consider using [Direct Mode](https://firecore.com/blog/infuse-77-direct-mode) for even faster updates.
