### ISSUE TITLE
Add Support for Emby 4.8

### ISSUE THREAD

**Issue by xjasonlyu** [firecore/InfuseSync#23]
Starting with Emby `4.8.x`, a new `BasePluginSimpleUI` class is introduced for emby plugins as its configuration page/UI. 

Previous web/html based config page is no longer worked (not editable) on the latest Emby version.

Ref: <https://dev.emby.media/>

**Comment by firecore** [comment]
The release version of 1.5.0 is now available in the Emby plugin catalog.
