### ISSUE TITLE
InfuseSync Updates for Jellyfin 10.7

### ISSUE THREAD

**Issue by anthonylavado** [firecore/InfuseSync#5]
For the upcoming release of Jellyfin, there are some plugin ABI changes.

From the [10.7 RC1 Release Notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc1):

> ## Client/Plugin (API/ABI) Developer Notes
> 
> * We have migrated from ServiceStack to ASP.NET. Web API endpoints no longer accept HTTP Form requests; everything must be `application/json`. NOTE: Plugins that implement endpoints will also have to migrate.
> * Plugins must now target `net5.0`.
> * `IHttpClient` removal: Now inject `IHttpClientFactory` instead.
> * `HttpException` removal: Now catch `HttpResponseException` instead.
> * Services can be registered to the DI pipeline.
> 
> Please see the [Jellyfin Development Matrix channel](https://matrix.to/#/#jellyfin-dev:matrix.org) for questions or further details on these changes.

**Comment by firecore** [comment]
InfuseSync v1.3.1 adds ASP.NET Core MVC controller to support Jellyfin 10.7.0
https://github.com/firecore/InfuseSync/releases/tag/v1.3.1
