### ISSUE TITLE
InfuseSync is Automatically Installed on Jellyfin

### ISSUE THREAD

**Issue by anthonylavado** [firecore/InfuseSync#6]
It appears that InfuseSync is automatically installed by the Infuse client. If the user is an Administrator, it makes a request to the Jellyfin server to locate the package in the repository, and it will install it. While the plugin is definitely useful, this process has caused some confusion with our users, resulting in support tickets.

Is it possible to have a prompt for this?

**Comment by firecore** [comment]
The 6.5.9 version of Infuse for iOS/tvOS now includes a toggle so users can opt-out of installing the InfuseSync plugin when setting up new Emby/Jellyfin shares.

![2021-01-18 11 30 51](https://user-images.githubusercontent.com/530706/104951894-aabb0000-5980-11eb-8220-641642e5c1d3.png)
