### ISSUE TITLE
Publish DLL for future releases?

### ISSUE THREAD

**Issue by nwithan8** [firecore/InfuseSync#8]
In future releases, could you pre-compile the DLL and publish that on GitHub?
I was able to build it myself, but it would make it a lot easier for other users and automation if they could download the DLL directly and not have to worry about dotnet CLI work

**Comment by anthonylavado** [comment]
I don't represent Firecore (I'm from Jellyfin), but as far as I know, they always have? It's listed in the releases section: https://github.com/firecore/InfuseSync/releases

Just download the zip you need, and extract it :-)
