### ISSUE TITLE
[Jellyfin] Move Plugin to Root of ZIP

### ISSUE THREAD

**Issue by anthonylavado** [firecore/InfuseSync#9]
Hey there!
The 1.3.2 pre-release is working perfectly with the now released version of 10.7. There's just one quirk - the plugin DLL should be at the root of the ZIP file instead of in a subdirectory.

To help with this I have created the required ZIP and we are currently serving that to 10.7.0 users from the Jellyfin repository.

**Comment by firecore** [comment]
Thanks @anthonylavado! Switched to the new structure starting [v1.3.3](https://github.com/firecore/InfuseSync/releases/tag/v1.3.3).
